name: CI

on:
  push:
    branches:
      - '**'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: yarn install
