# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ master ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - run: yarn install
      - name: version up
        run: |
          git config --global user.name 'choisohyun'
          git config --global user.email sohyun4283@naver.com
          yarn semantic-release
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}